### ISSUE TITLE
saving timeseries and FFT as txt files

### ISSUE THREAD

**Issue by skgrunblatt** [nksaunders/giants#2]
easy enough to add these to the quicklook loop?

`np.savetxt(str(dataa['ID'][i])+'.dat.ts', np.transpose([time,flux]), fmt='%.8f', delimiter='     ')`
`np.savetxt(str(dataa['ID'][i])+'.dat.ts.fft', np.transpose([freqq, fts]), fmt='%.8f', delimiter='     ')`

**Comment by nksaunders** [comment]
Implemented!
