### ISSUE TITLE
adding ACF inset

### ISSUE THREAD

**Issue by skgrunblatt** [nksaunders/giants#3]
lines to add:

`from mpl_toolkits.axes_grid1.inset_locator import inset_axes`

`acf = np.correlate(power,power, 'same')`
`freq_acf = np.linspace(-freq[-1],freq[-1],len(freq))`

and immediately after FFT plot calls:
`ax = plt.gca()`
`axins = inset_axes(ax, width=2.0, height=1.4)`
`axins.plot(freq_acf,acf)`
`axins.set_xlim(1,25)`
`axins.set_xlabel("ACF [uHz]")`

**Comment by nksaunders** [comment]
Implemented!
