### ISSUE TITLE
using lomb.py to calculate FFT

### ISSUE THREAD

**Issue by skgrunblatt** [nksaunders/giants#4]
[lomb.py.zip](https://github.com/nksaunders/giants/files/3773731/lomb.py.zip)
`import lomb`
`osample=5.`
`nyq=283.`

`freqq, amp, nout, jmax, prob = lomb.fasper(time,flux, osample, 3.)`
`freqq = 1000.*freqq/86.4`
`binn = freqq[1]-freqq[0]`
`fts = 2.*amp*np.var(flux*1e6)/(np.sum(amp)*binn)`
`fts = scipy.ndimage.filters.gaussian_filter(fts, 4)`

freqq and fts correspond to frequency and power of FFT.

**Comment by nksaunders** [comment]
Implemented!
